// @ts-nocheck
'use client'
import { useState } from 'react'
import { AlertTriangle, ListChecks } from 'lucide-react'
import type { Risk, RiskBlock } from '@/types/risk'
const badge:any={low:'border-emerald-200 bg-emerald-50 text-emerald-700',medium:'border-amber-200 bg-amber-50 text-amber-700',high:'border-red-200 bg-red-50 text-red-700',critical:'border-red-200 bg-red-50 text-red-700'}
function Blocks({blocks=[]}:{blocks:RiskBlock[]}){return <div className="space-y-4">{blocks.map((b,i)=><Block key={i} block={b}/>)}</div>}
function Block({block:b}:{block:RiskBlock}){if(b.type==='divider')return <hr className="border-slate-200"/>;if(b.type==='text'||b.type==='callout')return <div className={b.type==='callout'?'rounded-lg border border-amber-200 bg-amber-50 p-3':''}>{b.title&&<h4 className="mb-1 text-xs font-bold uppercase text-slate-500">{b.title}</h4>}<p className={`text-sm ${b.bold?'font-bold':''} ${b.status==='critical'?'text-red-700':'text-slate-700'}`}>{b.text}</p></div>;if(b.type==='metrics'){const items=b.items||[];return <div><Title t={b.title}/><div className="grid grid-cols-2 gap-2">{items.map((x:any,j:number)=><div key={j} className="rounded-lg border bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-slate-500">{x.label}</p><p className={`mt-1 text-lg font-bold ${x.status==='critical'?'text-red-600':x.status==='good'?'text-emerald-700':'text-slate-900'}`}>{x.value}</p></div>)}</div></div>};if(b.type==='key_value'){return <div><Title t={b.title}/><dl className="space-y-2">{(b.items||[]).map((x:any,j:number)=><div key={j} className="grid grid-cols-[130px_1fr] gap-3 text-sm"><dt className="font-semibold text-slate-500">{x.label}</dt><dd className="text-slate-800">{x.value}</dd></div>)}</dl></div>};if(b.type==='bullet_list'||b.type==='numbered_list')return <div><Title t={b.title}/><ol className={`${b.type==='numbered_list'?'list-decimal':'list-disc'} space-y-1 pl-5 text-sm text-slate-700`}>{(b.items||[]).map((x:any,j:number)=><li key={j}>{typeof x==='string'?x:x.text||x.title}</li>)}</ol></div>;if(b.type==='action_list')return <div><Title t={b.title}/><ol className="list-decimal space-y-2 pl-5 text-sm text-slate-700">{(b.items||[]).map((x:any,j:number)=><li key={j}><span className="font-medium">{x.title}</span>{x.owner&&<span className="ml-2 text-xs text-slate-400">Owner: {x.owner}</span>}</li>)}</ol></div>;if(b.type==='table'){const cols=Array.isArray(b.columns)?b.columns:[];return <div className="overflow-x-auto"><Title t={b.title}/><table className="w-full min-w-[520px] border-collapse text-left text-xs"><thead><tr>{cols.map((c:any)=><th key={c.key} className="border bg-slate-100 px-2 py-2 font-bold">{c.label}</th>)}</tr></thead><tbody>{(b.rows||[]).map((r:any,j:number)=><tr key={j}>{cols.map((c:any)=><td key={c.key} className="border px-2 py-2">{String(r[c.key]??'')}</td>)}</tr>)}</tbody></table></div>};return null}
function Title({t}:{t?:string}){return t?<h4 className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">{t}</h4>:null}
export function Preview({risk}:{risk:Risk}){const [view,setView]=useState<'notification'|'details'|'mitigation'>('notification');const v=risk.views?.[view]||{blocks:[]};return <div className="rounded-xl bg-slate-50 p-3"><article className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><AlertTriangle className="mt-1 size-5 text-red-500"/><div><h2 className="text-xl font-bold">{risk.title||'Risk notification'}</h2>{risk.subtitle&&<p className="mt-1 text-sm text-slate-500">{risk.subtitle}</p>}</div></div><span className={`rounded-full border px-2.5 py-1 text-xs font-bold ${badge[risk.severity]||badge.high}`}>{risk.severity_label||risk.severity}</span></div>{risk.summary&&<p className="my-5 text-sm leading-6 text-slate-700">{risk.summary}</p>}<Blocks blocks={v.blocks}/><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>setView('notification')} className="rounded-lg border px-3 py-2 text-xs font-semibold">Notification</button>{risk.views?.details?.blocks?.length>0&&<button onClick={()=>setView('details')} className="rounded-lg border px-3 py-2 text-xs font-semibold"><AlertTriangle className="mr-1 inline size-3"/> {risk.views.details.action_label||'View Details'}</button>}{risk.views?.mitigation?.blocks?.length>0&&<button onClick={()=>setView('mitigation')} className="rounded-lg border px-3 py-2 text-xs font-semibold"><ListChecks className="mr-1 inline size-3"/> {risk.views.mitigation.action_label||'Mitigation Plan'}</button>}</div></div><footer className="flex justify-between border-t px-5 py-3 text-[11px] text-slate-500"><span>{risk.sender?.source||risk.sender?.name} · Risk ID {risk.risk_id}</span><span>{risk.sender?.timestamp}</span></footer></article></div>}
