// @ts-nocheck
'use client'
import { ChevronDown, ChevronUp, Copy, Plus, Trash2 } from 'lucide-react'
import type { BlockType, RiskBlock, RiskViews } from '@/types/risk'
const input='w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-slate-400'
const types:BlockType[]=['text','callout','metrics','key_value','bullet_list','numbered_list','table','action_list','divider']
const empty=(type:BlockType):RiskBlock=> type==='table'?{type,title:'',columns:[{key:'column_1',label:'Column 1'},{key:'column_2',label:'Column 2'}],rows:[]}:type==='metrics'||type==='key_value'||type==='action_list'?{type,title:'',items:[]}:type==='bullet_list'||type==='numbered_list'?{type,title:'',items:[]}:{type,title:'',text:''}
const move=<T,>(a:T[],i:number,d:number)=>{const n=[...a],j=i+d;if(j<0||j>=n.length)return n;[n[i],n[j]]=[n[j],n[i]];return n}
export function GenericViewsEditor({views,onChange}:{views:RiskViews,onChange:(v:RiskViews)=>void}){
 const patch=(name:keyof RiskViews,blocks:RiskBlock[])=>onChange({...views,[name]:{...views[name],blocks}})
 return <div className="space-y-4">{(['notification','details','mitigation'] as const).map(name=><section key={name} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Generic View</p><h3 className="text-base font-bold capitalize">{name==='details'?'View Details':name==='mitigation'?'Mitigation Plan':'Notification'}</h3></div>{name!=='notification'&&<div className="mb-4 grid gap-3 sm:grid-cols-2"><input className={input} placeholder="View title" value={views[name].title||''} onChange={e=>onChange({...views,[name]:{...views[name],title:e.target.value}})}/><input className={input} placeholder="Button label" value={views[name].action_label||''} onChange={e=>onChange({...views,[name]:{...views[name],action_label:e.target.value}})}/></div>}<div className="space-y-3">{views[name].blocks.map((b,i)=><BlockEditor key={i} block={b} index={i} onChange={v=>patch(name,views[name].blocks.map((x,j)=>j===i?v:x))} onDelete={()=>patch(name,views[name].blocks.filter((_,j)=>j!==i))} onUp={()=>patch(name,move(views[name].blocks,i,-1))} onDown={()=>patch(name,move(views[name].blocks,i,1))} onCopy={()=>patch(name,[...views[name].blocks.slice(0,i+1),structuredClone(b),...views[name].blocks.slice(i+1)])}/>)}</div><div className="mt-4 flex flex-wrap gap-2">{types.map(t=><button key={t} type="button" onClick={()=>patch(name,[...views[name].blocks,empty(t)])} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-2 text-xs font-semibold hover:bg-slate-50"><Plus className="size-3"/>{t.replaceAll('_',' ')}</button>)}</div></section>)}</div>
}
function BlockEditor({block,index,onChange,onDelete,onUp,onDown,onCopy}:{block:RiskBlock,index:number,onChange:(b:RiskBlock)=>void,onDelete:()=>void,onUp:()=>void,onDown:()=>void,onCopy:()=>void}){const patch=(p:Partial<RiskBlock>)=>onChange({...block,...p});return <div className="rounded-xl border border-slate-200 bg-slate-50/70 p-3"><div className="mb-3 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><span className="rounded bg-slate-900 px-2 py-1 text-[10px] font-bold uppercase text-white">{block.type.replaceAll('_',' ')}</span><span className="text-xs text-slate-400">Block {index+1}</span></div><div className="flex"><button onClick={onUp} className="p-1"><ChevronUp className="size-4"/></button><button onClick={onDown} className="p-1"><ChevronDown className="size-4"/></button><button onClick={onCopy} className="p-1"><Copy className="size-4"/></button><button onClick={onDelete} className="p-1 text-red-500"><Trash2 className="size-4"/></button></div></div>{block.type!=='divider'&&<input className={input} placeholder="Block title (optional)" value={block.title||''} onChange={e=>patch({title:e.target.value})}/>} {(block.type==='text'||block.type==='callout')&&<textarea className={`${input} mt-2 min-h-24`} placeholder="Text" value={block.text||''} onChange={e=>patch({text:e.target.value})}/>} {(block.type==='metrics'||block.type==='key_value')&&<Pairs block={block} onChange={patch}/>} {(block.type==='bullet_list'||block.type==='numbered_list')&&<Strings block={block} onChange={patch}/>} {block.type==='action_list'&&<Actions block={block} onChange={patch}/>} {block.type==='table'&&<Table block={block} onChange={patch}/>}</div>}
function Pairs({block,onChange}:{block:RiskBlock,onChange:(p:Partial<RiskBlock>)=>void}){const items=(block.items||[]) as any[];return <div className="mt-2 space-y-2">{items.map((x,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-2"><input className={input} placeholder="Label" value={x.label||''} onChange={e=>onChange({items:items.map((v,j)=>j===i?{...v,label:e.target.value}:v)})}/><input className={input} placeholder="Value" value={x.value||''} onChange={e=>onChange({items:items.map((v,j)=>j===i?{...v,value:e.target.value}:v)})}/><button onClick={()=>onChange({items:items.filter((_,j)=>j!==i)})}><Trash2 className="size-4 text-red-500"/></button></div>)}<button className="text-xs font-semibold" onClick={()=>onChange({items:[...items,{label:'',value:''}]})}>+ Add item</button></div>}
function Strings({block,onChange}:{block:RiskBlock,onChange:(p:Partial<RiskBlock>)=>void}){const items=(block.items||[]) as string[];return <div className="mt-2 space-y-2">{items.map((x,i)=><div key={i} className="flex gap-2"><input className={input} value={x} placeholder="List item" onChange={e=>onChange({items:items.map((v,j)=>j===i?e.target.value:v)})}/><button onClick={()=>onChange({items:items.filter((_,j)=>j!==i)})}><Trash2 className="size-4 text-red-500"/></button></div>)}<button className="text-xs font-semibold" onClick={()=>onChange({items:[...items,'']})}>+ Add item</button></div>}
function Actions({block,onChange}:{block:RiskBlock,onChange:(p:Partial<RiskBlock>)=>void}){const items=(block.items||[]) as any[];return <div className="mt-2 space-y-2">{items.map((x,i)=><div key={i} className="grid gap-2 rounded-lg border bg-white p-2 sm:grid-cols-2"><input className={input} placeholder="Action title" value={x.title||''} onChange={e=>onChange({items:items.map((v,j)=>j===i?{...v,title:e.target.value,order:i+1}:v)})}/><input className={input} placeholder="Owner (optional)" value={x.owner||''} onChange={e=>onChange({items:items.map((v,j)=>j===i?{...v,owner:e.target.value}:v)})}/></div>)}<button className="text-xs font-semibold" onClick={()=>onChange({items:[...items,{order:items.length+1,title:'',owner:''}]})}>+ Add action</button></div>}
function Table({block,onChange}:{block:RiskBlock,onChange:(p:Partial<RiskBlock>)=>void}){const cols=Array.isArray(block.columns)?block.columns:[],rows=block.rows||[];const key=(s:string,i:number)=>(s.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||`column_${i+1}`);return <div className="mt-3 space-y-3"><div><p className="mb-1 text-xs font-bold">Columns</p>{cols.map((c,i)=><div key={i} className="mb-2 flex gap-2"><input className={input} value={c.label} placeholder="Column label" onChange={e=>{const old=c.key,nk=key(e.target.value,i),nc=cols.map((v,j)=>j===i?{key:nk,label:e.target.value}:v),nr=rows.map(r=>{const q={...r};q[nk]=q[old]??'';if(nk!==old)delete q[old];return q});onChange({columns:nc,rows:nr})}}/><button onClick={()=>onChange({columns:cols.filter((_,j)=>j!==i),rows:rows.map(r=>{const q={...r};delete q[c.key];return q})})}><Trash2 className="size-4 text-red-500"/></button></div>)}<button className="text-xs font-semibold" onClick={()=>onChange({columns:[...cols,{key:`column_${cols.length+1}`,label:`Column ${cols.length+1}`} ]})}>+ Add column</button></div><div><p className="mb-1 text-xs font-bold">Rows</p>{rows.map((r,ri)=><div key={ri} className="mb-2 grid gap-2 rounded-lg border bg-white p-2" style={{gridTemplateColumns:`repeat(${Math.max(cols.length,1)},minmax(0,1fr)) 28px`}}>{cols.map(c=><input key={c.key} className={input} placeholder={c.label} value={String(r[c.key]??'')} onChange={e=>onChange({rows:rows.map((v,j)=>j===ri?{...v,[c.key]:e.target.value}:v)})}/>) }<button onClick={()=>onChange({rows:rows.filter((_,j)=>j!==ri)})}><Trash2 className="size-4 text-red-500"/></button></div>)}<button className="text-xs font-semibold" onClick={()=>onChange({rows:[...rows,Object.fromEntries(cols.map(c=>[c.key,'']))]})}>+ Add row</button></div></div>}
